name: Deploy Kursach App

on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      shell: powershell
      run: docker build -t kursach .
    
    - name: Stop and remove old container
      shell: powershell  # Явно указываем PowerShell
      run: |
        try { docker stop kursach } catch { Write-Host "Контейнер уже остановлен" }
        try { docker rm kursach } catch { Write-Host "Контейнер уже удален" }
    
    - name: Run new container
      shell: powershell
      run: |
        docker run -d `
          -p 80:80 `
          --name kursach `
          kursach
