name: Build and Deploy Flask App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t flask-app .
        
    - name: Run container
      run: |
        docker stop myapp || true
        docker rm myapp || true  
        docker run -d -p 80:80 --name myapp flask-app
