name: Docker Build and Deploy (Windows)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u makarmatelenok --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t makarmatelenok/kursach:latest .
        docker push makarmatelenok/kursach:latest

  deploy:
    needs: build
    runs-on: self-hosted  
    env:
      DOCKER_HOST: "npipe:////./pipe/docker_engine"  
    
    steps:
    - name: Stop and remove old container 
      run: |
        docker stop nodejs-app || exit 0
        docker rm nodejs-app || exit 0

    - name: Clean unused images 
      run: docker image prune -a -f

    - name: Pull latest image
      run: docker pull makarmatelenok/kursach:latest

    - name: Run new container 
      run: |
        docker run -d -p 80:80 --name nodejs-app makarmatelenok/kursach:latest
