name: Docker Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Check WSL status
      shell: powershell
      run: |
        Write-Output "Проверка WSL..."
        wsl --status
        wsl --list --verbose
        
    - name: Stop and remove container (Pure Docker)
      shell: powershell
      run: |
        # Альтернатива без WSL
        try {
          docker stop python-app
          Write-Output "Контейнер остановлен"
        } catch {
          Write-Output "Контейнер уже остановлен"
        }
        
        try {
          docker rm python-app
          Write-Output "Контейнер удален"
        } catch {
          Write-Output "Контейнер уже удален"
        }

    - name: Run new container
      shell: powershell
      run: |
        docker run -d -p 80:80 --name python-app makarmatelenok/kursach:latest
    - name: Run container
      shell: powershell
      run: |
        wsl -e bash -c "docker run -d -p 80:80 --name python-app makarmatelenok/kursach:latest"
