name: Deploy Kursach App  # Изменил название для ясности

on: 
  push:
    branches: ["main"]  # Срабатывает при пуше в main ветку

jobs:
  deploy:
    runs-on: self-hosted  # Запуск на вашем ПК
    
    steps:
    # 1. Забираем код из репозитория
    - uses: actions/checkout@v4
    
    # 2. Собираем образ (теперь с именем kursach)
    - name: Build Docker image
      run: docker build -t kursach .  # Изменил имя образа
    
    # 3. Останавливаем и удаляем старый контейнер
    - name: Stop and remove old container
      run: |
        docker stop kursach || true  # Изменил имя контейнера
        docker rm kursach || true    # Изменил имя контейнера
    
    # 4. Запускаем новый контейнер
    - name: Run new container
      run: |
        docker run -d \
          -p 80:80 \
          --name kursach \  # Изменил имя контейнера
          kursach  # Используем новый имя образа
