name: Docker Build and Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest  # Сборка всегда на Linux
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u makarmatelenok --password-stdin

    - name: Build and push
      run: |
        docker build --platform linux/amd64 -t makarmatelenok/kursach:latest .
        docker push makarmatelenok/kursach:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Windows с WSL2
    steps:
    - name: Initialize WSL2
      shell: powershell
      run: |
        wsl --set-default-version 2
        wsl --update
        docker version --format '{{.Server.Os}}'  # Проверка режима Docker

    - name: Stop and remove container (WSL2 compatible)
      shell: powershell
      run: |
        wsl -e bash -c "docker stop python-app || true"
        wsl -e bash -c "docker rm python-app || true"

    - name: Run container
      shell: powershell
      run: |
        wsl -e bash -c "docker run -d -p 80:80 --name python-app makarmatelenok/kursach:latest"
