name: Docker Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Check Docker
      shell: powershell
      run: |
        docker --version
        docker ps -a
        
    - name: Stop container if exists
      shell: powershell
      run: |
        $containerId = docker ps -q -f name=python-app
        if ($containerId) {
          docker stop $containerId
          Write-Host "Container stopped"
        } else {
          Write-Host "No running container found"
        }
        
    - name: Remove container if exists
      shell: powershell
      run: |
        $containerId = docker ps -a -q -f name=python-app
        if ($containerId) {
          docker rm $containerId
          Write-Host "Container removed"
        } else {
          Write-Host "No container found"
        }
        
    - name: Pull latest image
      shell: powershell
      run: |
        docker pull makarmatelenok/kursach:latest
        
    - name: Run container
      shell: powershell
      run: |
        docker run -d -p 80:80 --name python-app makarmatelenok/kursach:latest
        docker ps -a
    - name: Run container
      shell: powershell
      run: |
        wsl -e bash -c "docker run -d -p 80:80 --name python-app makarmatelenok/kursach:latest"
