name: pipeline

on:
  push:
    branches:
      - main       # Запуск при пуше в главную ветку
      - feature/** # Запуск при пуше в ветки, начинающиеся с feature/
  pull_request:
    branches:
      - main       # Запуск при создании Pull Request в главную ветку

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${GITHUB_SHA} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${GITHUB_SHA}

  deploy-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production' # Запускать только для ветки production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Deploy to Production
        run: |
          echo "Deploying to Production Environment..."
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${GITHUB_SHA}
          docker run -p 80:80 -d ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${GITHUB_SHA}
