name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main  # Триггер на пуше в ветку main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest .

  push:
    runs-on: self-hosted
    needs: build  # Зависит от джобы build

    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest

  deploy:
    runs-on: self-hosted
    needs: push  # Зависит от джобы push

    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Deploy to server
      run: |
        $dockerUsername = "${{ secrets.DOCKER_HUB_USERNAME }}"
        $imageName = "$dockerUsername/kursach:latest"
        $containerName = "kursach"
    
        # Pull the latest Docker image
        docker pull $imageName
    
        # Stop and remove the existing container if it exists
        if (docker ps -a --filter "name=$containerName" --format '{{.Names}}' | Select-String -Pattern $containerName) {
            docker stop $containerName
            docker rm $containerName
        }
    
        # Run the new container
        docker run -d -p 80:80 --name $containerName $imageName
