name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main  # Триггер на пуше в ветку main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest .

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest

    - name: Deploy to server
      run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest &&
          docker stop kursach || true &&
          docker rm kursach || true &&
          docker run -d -p 80:80 --name kursach ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest
