name: Docker Build, Push, and Deploy

on:
  push:
    branches:
      - main  # Триггер на пуше в ветку main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest .

    - name: Save Docker image as artifact
      run: docker save -o kursach-image.tar ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4  # Используем v4 вместо v3
      with:
        name: kursach-image
        path: kursach-image.tar

  push:
    runs-on: ubuntu-latest
    needs: build  # Зависит от джобы build

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4  # Используем v4 вместо v3
      with:
        name: kursach-image
        path: .

    - name: Load Docker image
      run: docker load -i kursach-image.tar

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push  # Зависит от джобы push

    steps:
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Deploy to server
      run: |
        docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest &&
        docker stop kursach || true &&
        docker rm kursach || true &&
        docker run -d -p 80:80 --name kursach ${{ secrets.DOCKER_HUB_USERNAME }}/kursach:latest
